### PR TITLE
fix: update Angular to v14 and remove flex-layout as a dependency

### PR DESCRIPTION
**Pull request by ViliMakinen**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Updated to use Angular v14:
 - all Angular dependencies updated to their latest version
 - typescript updated to 4.6.3 to be compatible with Angular 14
 - removed flex-layout as a dependency since it was barely used and it does not support Angular 14. The functionality of the demo 
    stays the same.

* **What is the current behavior?** (You can also link to an open issue here)

Projects using this library get peer dependency warnings when trying to update to Angular v14.

* **What is the new behavior (if this is a feature change)?**

Projects using this library can now upgrade to Angular v14 without peer dependency warnings.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Yes, the package now requires users to use Angular v14.

* **Other information**:

Unit tests don't pass locally - I'm interested to see if they pass when run in the CI pipeline. (`const scrollbarWidth = '15px'` in the `ngx-drag-scroll.component.spec.ts` needs to be changed to `'17px'` to get tests to pass when run locally);

### CODE REVIEW

**Comment by Schloesslin** [comment]
Bonjour,

Quand est-ce que ce fix va être poussé ? C'est assez bloquant comme bug.

Merci :)

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Review by bfwg — CHANGES_REQUESTED** [review]
Looks like the ci step is borken.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular-devkit/build-angular@14.0.[5](https://github.com/bfwg/ngx-drag-scroll/runs/7454437942?check_suite_focus=true#step:4:6)
npm ERR! Found: ng-packagr@13.2.1
npm ERR! node_modules/ng-packagr
npm ERR!   dev ng-packagr@"13.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ng-packagr@"^14.0.0" from @angular-devkit/build-angular@14.0.5
npm ERR! node_modules/@angular-devkit/b
```

**Review by bfwg — CHANGES_REQUESTED** [review]
Hi @ViliMakinen  the CI tests are failing still. You should be able to reproduce the errors by running `ng test --watch=false "ngx-drag-scroll" "--watch=false" "--browsers=ChromeHeadless`

**Comment by ViliMakinen** [comment]
@bfwg thanks for the heads up! The CI tests are failing due to Angular CLI requiring a Node version of 14.15 or 16.10 or higher. Currently the CI pipeline uses a Node version of 12.

I'll remove the Node version 12 from the node-version matrix in the `ci.yml` if that's alright!

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
14.0.0-beta.2 is out with your change. Great work 🚀

**Pull request merged**
