### PR TITLE
feat(*): update peerDependencies for Angular v10

### PR DESCRIPTION
**Pull request by localpcguy**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Unit tests are passing `ng test`
- [ ] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature - update peerDependencies for Angular v10 

* **What is the current behavior?** (You can also link to an open issue here)
When you try to use with Angular v10 it gives a warning about not having the proper peer dependencies

* **What is the new behavior (if this is a feature change)?**
Works with Angular v10 without warnings

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Tested it with my app and it performed as expected

* **Other information**:

### CODE REVIEW

**Comment by localpcguy** [comment]
cc: @bfwg we are moving to v10, currently getting warnings related to this.

**Comment by localpcguy** [comment]
I actually added that because the root one was not being picked up when I did something like npm install in the projects directory. So I just copied the default one from root. I can remove it, but thought it could be useful in preventing unwanted files from ending up in the repo.

**Comment by bfwg** [comment]
We are not suppose to generate any files directly in the project directory so I think it is safe to remove the gitignore from the project/library folder.

**Comment by localpcguy** [comment]
Sounds good - I've removed the `.gitignore` file.

**Comment by bfwg** [comment]
9.0.0 beta-3 is out with the change

**Pull request merged**
