### PR TITLE
fix: patch to direction:rtl flipped the content. fixing logic instead

### PR DESCRIPTION
**Pull request by eyal-elkevity**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bug fix

* **What is the current behavior?** (You can also link to an open issue here)
after my last commit to support direction:rtl, Move functions worked but the content got flipped. See I wanted to keep the existing "math" logic and just trick the browser... but the content got flipped. so I removed the flipping code and instead changed the scrollLeft calcs to support negatives (it was just 3 tiny places. rest of commit is actually removing of the old fix).

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by eyal-elkevity** [comment]
I've added another commit to this PR, sorry I thought it would create a new one. it's just that if you don't use scrollbar-hidden="true" - when calling moveTo() with a high number (like in the demo, click the "last" button) - it actually moves the index there, because calculating the containerWidth fails. This happens since neither local members "wrapper" nor "parentNode" are initialized. so not to harm existing code - I didn't force any initialization - just added another "||" to the width calculation with the actual parent.

**Comment by bfwg** [comment]
Should we revert https://github.com/bfwg/ngx-drag-scroll/pull/293?

**Comment by eyal-elkevity** [comment]
> Should we revert #293?

well actually this commit cleans the code from that commit and introduces an actual fix to direction:rtl

**Review by bfwg — APPROVED** [review]
LGTM

**Pull request merged**
