### PR TITLE
fix: prevent click on drag end (close #154)

### LINKED ISSUE #154: Click propagation
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

I'm having some problems when I drag and release the click, the event seems to not be stopping its propagation as the "Issue #54 - fix: prevent click propagation immediately after drag and drop" says.

  - Version: 1.8.2
  - Browser: all desktop browser

### LINKED ISSUE #222: Drag start and drag end output event
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

### PR DESCRIPTION
**Pull request by dintecom**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Prevent click on mouse drag end by setting pointerEvents to none until dragging (close #154).

* **What is the current behavior?** (You can also link to an open issue here)
After mouse button up while dragging, the item under the cursor is clicked in some cases.

* **What is the new behavior (if this is a feature change)?**
Clicking on an element will occur only if there was no drag.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by dintecom** [comment]
I removed from this pull request all unnecessary. Unfortunately, I still can’t check it on a touchpad device. I would be grateful if you check it again with your touchpad.

**Comment by bfwg** [comment]
For sure, I can help you with testing on a touchpad. Do you mind to resolve the conflicts before I test?

**Comment by bfwg** [comment]
Unfortunately, merging #237 has made some new conflicts.

**Comment by dintecom** [comment]
Version 7.4.1 in npm does not contain this hotfix?

**Comment by bfwg** [comment]
It does, I forget to push the 7.4.1 commit. I’ll do that shortly.

**Comment by bfwg** [comment]
You are right, it wasn't in 7.4.1 by mistake. I've included in 7.4.2. Great catch.

**Comment by dintecom** [comment]
Thank you very much for the work done!

**Pull request merged**
