### PR TITLE
Ng 17 support

### PR DESCRIPTION
**Pull request by tylerstarcher**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces support for Angular 17 as well as introduces standalone for the component and directive.

* **What is the current behavior?** (You can also link to an open issue here)
The current behavior only supports Angular 16. #323

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
This PR has breaking changes in that the DragScrollModule is no longer available.

* **Other information**:

### CODE REVIEW

**Comment by tylerstarcher** [comment]
This is my first contribution so please let me know if anything is out of order. #323 is resolved by this PR as well.

**Comment by tylerstarcher** [comment]
@bfwg any chance you can take a look at this?

**Comment by bfwg** [comment]
The CI is failing with below error. Looks like we need to update https://github.com/bfwg/ngx-drag-scroll/blob/develop/.github/workflows/ci.yml#L19
```
Run npm run test ngx-drag-scroll -- --watch=false --browsers=ChromeHeadless

> ngx-drag-scroll-demo@0.0.0 test
> ng test --watch=false ngx-drag-scroll --watch=false --browsers=ChromeHeadless

Node.js version v1[6](https://github.com/bfwg/ngx-drag-scroll/actions/runs/7253494775/job/19842404329?pr=325#step:6:7).20.2 detected.
The Angular CLI requires a minimum Node.js version of v1[8](https://github.com/bfwg/ngx-drag-scroll/actions/runs/7253494775/job/19842404329?pr=325#step:6:9).13.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.

Error: Process completed with exit code 3.
```

**Comment by tylerstarcher** [comment]
Thanks! Updated to 18.x

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
17.0.1 is out with your changes. Great work.

**Pull request merged**
