### PR TITLE
feat: ng-16 support

### PR DESCRIPTION
**Pull request by maranmaran**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds support for Angular 16

* **What is the current behavior?** (You can also link to an open issue here)
Can't resolve common dependencies when upgrading to NG-16

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by maranmaran** [comment]
Hi! First-time contributor, let me know if I missed something.

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by maranmaran** [comment]
@bfwg Heyo, is it possible to get this rolling 😄

**Comment by bfwg** [comment]
Totally, I'll review it today.

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
16.0.0 is out with this change. Nice work!

**Pull request merged**
