### PR TITLE
Implement fix for #250

### PR DESCRIPTION
**Pull request by Thomas1664**
* **Please check if the PR fulfils these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [ ] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, …)
Bugfix for #250 

* **Other information**:
Check if ```_scrollbarHidden``` is true. If so, call ```disableScroll()```.

### CODE REVIEW

**Comment by Thomas1664** [comment]
Not sure why this test fails. Has nothing to do with my changes

**Comment by bfwg** [comment]
@Thomas1664  The CI is passing on develop so there must be an issue with the change. We shouldn't disable scroll when the drag scroll item is smaller than the container.
https://github.com/bfwg/ngx-drag-scroll/blob/6c767b4fc1e15d467c435be871cfb4506888e3ad/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.spec.ts#L338-L339

**Comment by Thomas1664** [comment]
As you can see in the test logs you have some vulnerabilities in the devDependencies and you use Angular 9 but the latest version is Angular 10. You should consider to update Angular.

**Review by bfwg — APPROVED** [review]
Nice work. LGTM 💯

**Comment by bfwg** [comment]
9.0.0 beta-4 is out with this change

**Pull request merged**
