### PR TITLE
feat: update packages

### PR DESCRIPTION
**Pull request by MrSnappingTurtle**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/bfwg/ngx-drag-scroll/issues/228

* **What is the new behavior (if this is a feature change)?**
Upgraded packages including Angular 8

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by MrSnappingTurtle** [comment]
I've managed to upgrade the packages. The project builds fine and the test app in the browser seems to work fine but I get test errors which I'm not sure how to investigate given that I'm not familiar with the library. Could someone please take a look and point me in the right direction?

**Comment by bfwg** [comment]
Hi @MrSnappingTurtle , I couldn't get the unit tests to work as well. I feel the problem within the spec file.

**Comment by bfwg** [comment]
I got the tests fixed after hours of investigation. @MrSnappingTurtle Can you review my changes please?

**Comment by MrSnappingTurtle** [comment]
Sure, I'll try to take a look on Monday.

**Comment by MrSnappingTurtle** [comment]
Your code changes all look good to me. 👍 

The issue I'm having is that locally my tests seem to still fail. I've tried building/testing with both node 10 (as the CI runs) and 12. I've asked a colleague to try checking out the project and running the tests as well and he also had failures.

Is there something else that I have to do when testing locally? This is what I see on `3a55f8c` when running `npm run test ngx-drag-scroll`:

```zsh
ngx-drag-scroll on  feat-upgrade-packages is 📦 v0.0.0 via ⬢ v10.16.0 at ☸️ docker-for-desktop
➜ npm run test ngx-drag-scroll

> ngx-drag-scroll-demo@0.0.0 test /Users/dennissubachev/projects/ngx-drag-scroll
> ng test --watch=false "ngx-drag-scroll"

 12% building 18/18 modules 0 active01 07 2019 12:39:32.899:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
01 07 2019 12:39:32.902:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
01 07 2019 12:39:32.912:INFO [launcher]: Starting browser Chrome
01 07 2019 12:39:36.271:INFO [Chrome 75.0.3770 (Mac OS X 10.14.1)]: Connected on socket ngs6tVy5unSOM87cAAAA with id 33083571
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should not trying to hide the scrollbar when there are nothing to hide FAILED
	Error: Expected '70px' to be '50px'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:308:69
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 1 of 30 (1 FAILED) (0 secs / 0.105 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should not trying to hide the scrollbar when there are nothing to hide FAILED
	Error: Expected '70px' to be '50px'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:308:69
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
LOG: 'current index: 5'
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 1 of 30 (1 FAILED) (0 secs / 0.105 secs)
LOG: 'current index: 0'
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 1 of 30 (1 FAILED) (0 secs / 0.105 secs)
LOG: 'current index: 5'
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 2 of 30 (1 FAILED) (0 secs / 0.153 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should add pixels to the last item FAILED
	Error: Expected '20px' to be '15px'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:272:93
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 9 of 30 (2 FAILED) (0 secs / 1.323 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should add pixels to the last item FAILED
	Error: Expected '20px' to be '15px'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:272:93
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should only hide horizontal scroll bar FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:219:51
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 21 of 30 (3 FAILED) (0 secs / 4.232 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should only hide horizontal scroll bar FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:219:51
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should only hide vertical scroll bar FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:235:50
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 23 of 30 (4 FAILED) (0 secs / 4.263 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should only hide vertical scroll bar FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:235:50
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should hide all scroll bars FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:253:50
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:254:51
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 27 of 30 (5 FAILED) (0 secs / 4.865 secs)
Chrome 75.0.3770 (Mac OS X 10.14.1) DragScrollComponent should hide all scroll bars FAILED
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:253:50
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
	    at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-testing.js:770:1)
	Error: Expected 'calc(100% + 20px)' to be 'calc(100% + 15px)'.
	    at <Jasmine>
	    at src/lib/ngx-drag-scroll.component.spec.ts:254:51
	    at ZoneDelegate.invoke (Users/dennissubachev/projects/ngx-drag-scroll/node_modules/zone.js/dist/zone-evergreen.js:359:1)
Chrome 75.0.3770 (Mac OS X 10.14.1): Executed 30 of 30 (5 FAILED) (6.021 secs / 5.967 secs)
TOTAL: 5 FAILED, 25 SUCCESS
TOTAL: 5 FAILED, 25 SUCCESS
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-drag-scroll-demo@0.0.0 test: `ng test --watch=false "ngx-drag-scroll"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngx-drag-scroll-demo@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennissubachev/.npm/_logs/2019-07-01T19_39_44_408Z-debug.log
```

**Comment by bfwg** [comment]
Hi @MrSnappingTurtle , you are getting those errors because the scroll bar width of your local browser is different from the headless CI browser. If you look at [here](https://github.com/bfwg/ngx-drag-scroll/blob/3a55f8cb430ac4de6f0e162c63c14653ad6fc09c/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.spec.ts#L52), you can see that the scrollbar width is hard coded. So your tests will pass locally if you change it to match your browser.

**Comment by bfwg** [comment]
I've converted the PR to "ready for review" and I'll try to find time this week to do a thorough review if you are fine with the state of your PR.

**Comment by MrSnappingTurtle** [comment]
Sounds good! Let me know if you'd like me to rebase/squash or if there is anything else you need from me.

**Pull request merged**
