### PR TITLE
feat: angular v18 support

### PR DESCRIPTION
**Pull request by justAsascha**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces support for Angular 18.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by justAsascha** [comment]
@bfwg it's my first commit. Do you need any further information?

**Comment by bfwg** [comment]
Hi, looks like ci is failing. Can you try running 'npm ci' locally and make sure it passes?

**Comment by justAsascha** [comment]
Hi, i couldn't reproduce it on my local osx environment. I figured out it's somehow related to nx. However i found multiple threads with like [this](https://stackoverflow.com/questions/77989039/error-cannot-find-module-nx-nx-linux-x64-gnu). They recommend to install optional dependencies and install them on CI which seems to work.

**Comment by justAsascha** [comment]
@bfwg what do you think about it?

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
18.0.0 is out on npm. 🎉

**Pull request merged**
