### PR TITLE
fix: update peer dependencies to support angular 14

### PR DESCRIPTION
**Pull request by ViliMakinen**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Update the peer dependencies to support Angular 14.

* **What is the current behavior?** (You can also link to an open issue here)
The 14.0.0-beta.2 version still has the Angular 13 as its peer dependency.

* **What is the new behavior (if this is a feature change)?**
Update the peer dependencies to include Angular 14.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
In the previous PR, the peer dependencies were not updated correctly and the changelog was not updated, hence this PR. Sorry for the trouble!

### CODE REVIEW

**Comment by zmikolaj** [comment]
:thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup:

**Review by zmikolaj — APPROVED** [review]
:thumbsup:

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
14.0.1 is out with this PR. Thanks.

**Pull request merged**
