### PR TITLE
Use commitlint for better commit quality.

### LINKED ISSUE #95: Install commitlint
Most of the popular projects ( including Angular/* ) use a commitlint style of project to format the commits better ( distinguish between fix / feat etc. ) that comes in very handy during release logs. 

More details at: 
http://marionebl.github.io/commitlint/#/guides-local-setup . 

would be useful to have it injected in the project for better commit quality.

### PR DESCRIPTION
**Pull request by bfwg**
As per @akkumar , it commitlint would be good to have.
> Most of the popular projects ( including Angular/* ) use a commitlint style of project to format the commits better ( distinguish between fix / feat etc. ) that comes in very handy during release logs.

Closes #95

### CODE REVIEW

**Comment by akkumar** [comment]
The commit looks good. 

But not sure why the CI failed though. 

```console
@angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found instead.
```
May be - we need to bring typescript to 2.4.2 ?

**Comment by akkumar** [comment]
Ok - seems like the forceful fail test of foo prefix is the reason. Good to go..

**Comment by bfwg** [comment]
Thanks for reviewing @akkumar

**Comment by akkumar** [comment]
Also added issue #98 docs to note the list of types available for commit for future reference.

**Pull request merged**
