### PR TITLE
Feat: Support for angular 15

### PR DESCRIPTION
**Pull request by amit-rajbhandari**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Unit tests are passing `ng test`
- [x] Lint tests are passing `ng lint`

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds support for Angular 15.

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/bfwg/ngx-drag-scroll/issues/312

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by bfwg — CHANGES_REQUESTED** [review]
Hi @amit-rajbhandari , nice work. I can merge the PR once the code conflicts is resolved.

**Comment by amit-rajbhandari** [comment]
@bfwg Hi resolved the conflicts and removed material legacy dependencies as well please have a look.

**Review by bfwg — APPROVED** [review]
LGTM 👍

**Comment by bfwg** [comment]
15.0.0 is out in npm

**Pull request merged**
